const API=/^(?:localhost|127\.0\.0\.1)$/.test(location.hostname)?"http://127.0.0.1:8791":"https://fico-tracking-api.automacaofico.workers.dev",AXIS="../../mapa-superestrutura/assets/data/fico-axis-full.json";
const PACKAGES=[{id:"P01",start:0,end:38100,color:"#0075a9"},{id:"P02",start:38100,end:71300,color:"#55a646"},{id:"P03",start:71300,end:104500,color:"#ee7623"},{id:"P04",start:104500,end:131260,color:"#7b61a8"},{id:"P05",start:131260,end:167300,color:"#008a8a"},{id:"P06",start:167300,end:225000,color:"#c34f5d"},{id:"P07",start:225000,end:239950,color:"#657583"},{id:"P08",start:239950,end:292260,color:"#b27a19"}];
const $=id=>document.getElementById(id),els={clock:$("clock"),online:$("online"),unstable:$("unstable"),offline:$("offline"),noSignal:$("no-signal"),alertTotal:$("alert-total"),updated:$("updated"),alerts:$("alerts"),asideCount:$("aside-count"),fleet:$("fleet"),fit:$("fit"),fullscreen:$("fullscreen")};
let axis=[],grid=new Map(),map,equipment=[],markers=new Map(),packageMarkers=[],kmPopup;
const formatDate=v=>new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"medium"}).format(new Date(v));
const formatKm=m=>`${Math.floor(Math.max(0,Math.round(m))/1000)}+${String(Math.max(0,Math.round(m))%1000).padStart(3,"0")}`;
const status=x=>!x.receivedAt?"sem-sinal":Date.now()-Date.parse(x.receivedAt)<=30000?"online":Date.now()-Date.parse(x.receivedAt)<=120000?"unstable":"offline";
const age=v=>{const s=Math.max(0,(Date.now()-Date.parse(v))/1000);return s<60?`${Math.round(s)} s`:s<3600?`${Math.round(s/60)} min`:`${Math.round(s/3600)} h`};
const key=(lon,lat)=>`${Math.floor(lon/.02)}:${Math.floor(lat/.02)}`;
function prepare(points){axis=points;for(const p of points){const k=key(p.coordinate[0],p.coordinate[1]);if(!grid.has(k))grid.set(k,[]);grid.get(k).push(p)}}
function dist(a,b,c,d){const y=(d-b)*111320,x=(c-a)*111320*Math.cos((b+d)*Math.PI/360);return Math.hypot(x,y)}
function project(lon,lat){lon=Number(lon);lat=Number(lat);const gx=Math.floor(lon/.02),gy=Math.floor(lat/.02);let best;for(let x=gx-1;x<=gx+1;x++)for(let y=gy-1;y<=gy+1;y++)for(const p of grid.get(`${x}:${y}`)||[]){const d=dist(lon,lat,p.coordinate[0],p.coordinate[1]);if(!best||d<best.distanceM)best={stationM:p.station_m,distanceM:d,coordinate:p.coordinate}}return best}
function atStation(target){let lo=0,hi=axis.length-1;while(lo+1<hi){const m=(lo+hi)>>1;if(axis[m].station_m<=target)lo=m;else hi=m}const a=axis[lo],b=axis[hi],t=(target-a.station_m)/Math.max(1,b.station_m-a.station_m);return[a.coordinate[0]+t*(b.coordinate[0]-a.coordinate[0]),a.coordinate[1]+t*(b.coordinate[1]-a.coordinate[1])]}
function slice(start,end){return[atStation(start),...axis.filter(p=>p.station_m>start&&p.station_m<end).map(p=>p.coordinate),atStation(end)]}
function mapStyle(){return{version:8,sources:{osm:{type:"raster",tiles:["https://tile.openstreetmap.org/{z}/{x}/{y}.png"],tileSize:256,attribution:"© OpenStreetMap"},sat:{type:"raster",tiles:["https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"],tileSize:256,attribution:"Esri"}},layers:[{id:"osm",type:"raster",source:"osm"},{id:"sat",type:"raster",source:"sat",layout:{visibility:"none"}}]}}
function initMap(){map=new maplibregl.Map({container:"map",style:mapStyle(),center:[-50.3,-14.08],zoom:7.3,attributionControl:false});map.addControl(new maplibregl.NavigationControl({showCompass:false}),"bottom-left");map.on("load",()=>{const features=PACKAGES.map(p=>({type:"Feature",properties:p,geometry:{type:"LineString",coordinates:slice(p.start,Math.min(p.end,axis.at(-1).station_m))}}));map.addSource("packages",{type:"geojson",data:{type:"FeatureCollection",features}});map.addLayer({id:"package-case",type:"line",source:"packages",paint:{"line-color":"#fff","line-width":8}});map.addLayer({id:"packages",type:"line",source:"packages",paint:{"line-color":["get","color"],"line-width":5}});map.addLayer({id:"hit",type:"line",source:"packages",paint:{"line-color":"#fff","line-width":24,"line-opacity":.01}});packageMarkers=PACKAGES.map(p=>{const el=document.createElement("div");el.className="package-label";el.style.setProperty("--package",p.color);el.textContent=p.id;return new maplibregl.Marker({element:el}).setLngLat(atStation((p.start+Math.min(p.end,axis.at(-1).station_m))/2)).addTo(map)});map.on("mousemove","hit",ev=>{const pr=project(ev.lngLat.lng,ev.lngLat.lat);if(!pr)return;const pack=PACKAGES.find(p=>pr.stationM>=p.start&&pr.stationM<p.end);const d=document.createElement("div");d.className="km-pop";d.innerHTML="<span></span><strong></strong>";d.querySelector("span").textContent=pack?.id||"FICO";d.querySelector("strong").textContent=`KM ${formatKm(pr.stationM)}`;(kmPopup||=new maplibregl.Popup({closeButton:false,closeOnClick:false,offset:10})).setLngLat(ev.lngLat).setDOMContent(d).addTo(map)});map.on("mouseleave","hit",()=>kmPopup?.remove());render()})}
function alertsFor(list){const a=[];for(const x of list){const s=status(x),pr=x.receivedAt?project(x.longitude,x.latitude):null;if(s==="offline")a.push({high:true,title:`${x.equipmentId} offline`,text:`Sem atualização há ${age(x.receivedAt)} · ${x.operatorName||"sem operador"}`});else if(s==="unstable")a.push({title:`${x.equipmentId} instável`,text:`Último sinal há ${age(x.receivedAt)}`});if(x.receivedAt&&Number(x.battery)<20)a.push({title:`Bateria baixa · ${x.equipmentId}`,text:`Carga informada em ${x.battery}%`});if(x.receivedAt&&Number(x.accuracy)>40)a.push({title:`Precisão insuficiente · ${x.equipmentId}`,text:`Margem atual de ${Math.round(x.accuracy)} m`});if(pr&&pr.distanceM>100)a.push({high:true,title:`${x.equipmentId} fora da faixa`,text:`Sinal a ${Math.round(pr.distanceM)} m do eixo ferroviário`})}return a}
function updateMarker(x){if(!x.receivedAt)return;const pr=project(x.longitude,x.latitude);if(!pr)return;let marker=markers.get(x.equipmentId);if(!marker){const el=document.createElement("div");el.className="equipment-marker";el.dataset.label=x.equipmentId;marker=new maplibregl.Marker({element:el}).setLngLat(pr.coordinate).addTo(map);markers.set(x.equipmentId,marker)}marker.setLngLat(pr.coordinate);marker.getElement().className=`equipment-marker ${status(x)}`;marker.getElement().title=`${x.equipmentId} · KM ${formatKm(pr.stationM)} · ${x.operatorName||"sem operador"}`}
function render(){if(!equipment.length)return;const counts={online:0,unstable:0,offline:0,"sem-sinal":0};equipment.forEach(x=>counts[status(x)]++);els.online.textContent=counts.online;els.unstable.textContent=counts.unstable;els.offline.textContent=counts.offline;els.noSignal.textContent=counts["sem-sinal"];const alerts=alertsFor(equipment);els.alertTotal.textContent=alerts.length;els.asideCount.textContent=alerts.length;els.alerts.replaceChildren();if(!alerts.length)els.alerts.innerHTML='<div class="empty">Nenhum alerta ativo.</div>';for(const x of alerts){const d=document.createElement("div");d.className=`alert ${x.high?"high":""}`;d.innerHTML="<strong></strong><span></span>";d.querySelector("strong").textContent=x.title;d.querySelector("span").textContent=x.text;els.alerts.append(d)}els.fleet.replaceChildren();for(const x of equipment){const s=status(x),pr=x.receivedAt?project(x.longitude,x.latitude):null,b=document.createElement("button");b.className=`unit ${s}`;b.innerHTML="<strong></strong><span></span><span class=km></span><small></small>";b.querySelector("strong").textContent=x.equipmentId;b.querySelector("span").textContent=x.name||x.description||x.type;b.querySelector(".km").textContent=pr?`KM ${formatKm(pr.stationM)}`:"SEM SINAL";b.querySelector("small").textContent=x.receivedAt?`${x.operatorName||"Sem operador"} · ${Number(x.speed||0).toFixed(1)} km/h · ${age(x.receivedAt)}`:"Aguardando primeira posição";if(pr)b.onclick=()=>map.easeTo({center:pr.coordinate,zoom:14,duration:700});els.fleet.append(b);updateMarker(x)}}
function fit(){const b=new maplibregl.LngLatBounds();let n=0;for(const x of equipment)if(x.receivedAt){const p=project(x.longitude,x.latitude);if(p){b.extend(p.coordinate);n++}}if(n)map.fitBounds(b,{padding:90,maxZoom:13})}
async function load(){try{const r=await fetch(`${API}/api/v1/equipment/latest`,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();equipment=(d.equipment||[]).sort((a,b)=>a.equipmentId.localeCompare(b.equipmentId));els.updated.textContent=`Atualizado em ${formatDate(d.serverTime||new Date())} · ciclo de 5 s`;render()}catch(err){els.updated.textContent=`Falha na atualização · ${err.message}`}}
document.querySelectorAll("[data-basemap]").forEach(b=>b.onclick=()=>{const sat=b.dataset.basemap==="satellite";map.setLayoutProperty("osm","visibility",sat?"none":"visible");map.setLayoutProperty("sat","visibility",sat?"visible":"none");document.querySelectorAll("[data-basemap]").forEach(x=>x.classList.toggle("active",x===b))});els.fit.onclick=fit;els.fullscreen.onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();document.addEventListener("fullscreenchange",()=>els.fullscreen.textContent=document.fullscreenElement?"SAIR DA TELA CHEIA":"TELA CHEIA");setInterval(()=>els.clock.textContent=new Date().toLocaleTimeString("pt-BR"),1000);
fetch(AXIS).then(r=>r.json()).then(d=>{prepare(d.points);initMap();load();setInterval(load,5000)}).catch(err=>els.updated.textContent=`Traçado indisponível · ${err.message}`);
