import { GPS_DEADBAND_M, GPS_MAX_PRECISION_M, analyzeProjectedTrack } from "./motion.js";

const API=/^(?:localhost|127\.0\.0\.1)$/.test(location.hostname)?"http://127.0.0.1:8791":"https://fico-tracking-api.automacaofico.workers.dev";
const AXIS="../../mapa-superestrutura/assets/data/fico-axis-full.json";
const $=id=>document.getElementById(id), e={access:$("access"),accessForm:$("access-form"),password:$("password"),accessMessage:$("access-message"),dashboard:$("dashboard"),filters:$("filters"),equipment:$("equipment"),operator:$("operator"),from:$("from"),to:$("to"),message:$("message"),distance:$("distance"),moving:$("moving"),stopped:$("stopped"),utilization:$("utilization"),average:$("average"),maximum:$("maximum"),coverage:$("coverage"),source:$("source"),freshness:$("freshness"),chart:$("speed-chart"),sessions:$("sessions-body"),shiftCount:$("shift-count"),replayToggle:$("replay-toggle"),replaySpeed:$("replay-speed"),replayTime:$("replay-time"),replayRange:$("replay-range"),alerts:$("alerts-list"),alertCount:$("alert-count"),events:$("events-list"),eventCount:$("event-count"),print:$("print-report")};
let password="",axis=[],grid=new Map(),map,replayGroups=new Map(),replayMarkers=new Map(),replayStart=0,replayEnd=0,replayCurrent=0,replayTimer=null;
const isoLocal=d=>new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,16);
e.to.value=isoLocal(new Date());e.from.value=isoLocal(new Date(Date.now()-86400000));
const notify=(el,text)=>{el.textContent=text;el.hidden=!text};
const duration=s=>{s=Math.max(0,Math.round(s||0));return `${Math.floor(s/3600)}h ${String(Math.floor(s%3600/60)).padStart(2,"0")}min`};
const date=v=>v?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(v)):"Em andamento";
const age=s=>s<60?`${Math.round(s)} s`:s<3600?`${Math.round(s/60)} min`:`${Math.round(s/3600)} h`;
const gridKey=(lon,lat)=>`${Math.floor(lon/.02)}:${Math.floor(lat/.02)}`;
function prepareAxis(points){axis=points;for(const p of points){const key=gridKey(p.coordinate[0],p.coordinate[1]);if(!grid.has(key))grid.set(key,[]);grid.get(key).push(p)}}
function distanceMeters(a,b,c,d){const y=(d-b)*111320,x=(c-a)*111320*Math.cos((b+d)*Math.PI/360);return Math.hypot(x,y)}
function project(p){const lon=Number(p.longitude),lat=Number(p.latitude),gx=Math.floor(lon/.02),gy=Math.floor(lat/.02);let best=null;for(let x=gx-1;x<=gx+1;x++)for(let y=gy-1;y<=gy+1;y++)for(const c of grid.get(`${x}:${y}`)||[]){const d=distanceMeters(lon,lat,c.coordinate[0],c.coordinate[1]);if(!best||d<best.distanceM)best={stationM:c.station_m,distanceM:d,coordinate:c.coordinate}}return best}
function calculate(points,sessions){const sorted=[...points].sort((a,b)=>Date.parse(a.captured_at)-Date.parse(b.captured_at));sorted.forEach(p=>p.projection=project(p));const groups=sorted.reduce((o,p)=>((o[`${p.equipment_id}:${p.operator_registration||"-"}`]||=[]).push(p),o),{});const analyses=Object.values(groups).map(analyzeProjectedTrack),timeline=analyses.flatMap(a=>a.timeline).sort((a,b)=>Date.parse(a.captured_at)-Date.parse(b.captured_at));const speeds=timeline.map(p=>Number(p.effective_speed_mps)).filter(v=>Number.isFinite(v)&&v>=.5);const moving=analyses.reduce((s,a)=>s+a.movingS,0),stopped=analyses.reduce((s,a)=>s+a.stoppedS,0),observed=analyses.reduce((s,a)=>s+a.observedS,0),turnTime=sessions.reduce((s,x)=>s+Math.max(0,(Date.parse(x.ended_at||e.to.value)-Date.parse(x.started_at))/1000),0);return{timeline,tracks:analyses.map(a=>a.accepted),rail:analyses.reduce((s,a)=>s+a.distanceM,0),moving,stopped,observed,max:speeds.length?Math.max(...speeds):0,average:speeds.length?speeds.reduce((a,b)=>a+b,0)/speeds.length:0,coverage:turnTime?Math.min(100,observed/turnTime*100):0,rejected:analyses.reduce((s,a)=>s+a.rejectedCount,0),suppressed:analyses.reduce((s,a)=>s+a.suppressedCount,0)}}
function renderKpis(m){e.distance.textContent=`${(m.rail/1000).toLocaleString("pt-BR",{maximumFractionDigits:1})} km`;e.moving.textContent=duration(m.moving);e.stopped.textContent=duration(m.stopped);e.utilization.textContent=`${(m.moving/Math.max(1,m.moving+m.stopped)*100).toLocaleString("pt-BR",{maximumFractionDigits:0})}%`;e.average.textContent=`${(m.average*3.6).toLocaleString("pt-BR",{maximumFractionDigits:1})} km/h`;e.maximum.textContent=`${(m.max*3.6).toLocaleString("pt-BR",{maximumFractionDigits:1})} km/h`;e.coverage.textContent=`${m.coverage.toLocaleString("pt-BR",{maximumFractionDigits:0})}%`}
function renderSessions(items){e.sessions.replaceChildren();e.shiftCount.textContent=`${items.length} turno${items.length===1?"":"s"}`;if(!items.length){const r=e.sessions.insertRow(),c=r.insertCell();c.colSpan=6;c.textContent="Nenhum turno no período.";return}for(const x of items){const r=e.sessions.insertRow();[date(x.started_at),date(x.ended_at),`${x.operator_name} · ${x.operator_registration}`,x.equipment_id,x.ended_reason||"Em andamento",duration((Date.parse(x.ended_at||e.to.value)-Date.parse(x.started_at))/1000)].forEach(v=>{const c=r.insertCell();c.textContent=v})}}
function renderChart(points){e.chart.replaceChildren();const ns="http://www.w3.org/2000/svg",w=900,h=260,pad=34;if(!points.length){const t=document.createElementNS(ns,"text");t.setAttribute("x",450);t.setAttribute("y",135);t.setAttribute("text-anchor","middle");t.textContent="Sem posições no período";e.chart.append(t);return}const step=Math.max(1,Math.ceil(points.length/700)),sample=points.filter((_,i)=>i%step===0),start=Date.parse(points[0].captured_at),end=Date.parse(points.at(-1).captured_at),max=Math.max(10,...sample.map(p=>Number(p.effective_speed_mps||0)*3.6));for(let i=0;i<5;i++){const l=document.createElementNS(ns,"line"),y=pad+(h-pad*2)*i/4;l.setAttribute("x1",pad);l.setAttribute("x2",w-pad);l.setAttribute("y1",y);l.setAttribute("y2",y);l.setAttribute("stroke","#dce4e9");e.chart.append(l)}const path=document.createElementNS(ns,"path");path.setAttribute("d",sample.map((p,i)=>`${i?"L":"M"}${(pad+(w-pad*2)*(Date.parse(p.captured_at)-start)/Math.max(1,end-start)).toFixed(1)},${(h-pad-(h-pad*2)*(Number(p.effective_speed_mps||0)*3.6/max)).toFixed(1)}`).join(" "));path.setAttribute("fill","none");path.setAttribute("stroke","#2f7fc4");path.setAttribute("stroke-width","3");e.chart.append(path)}
function initMap(){map=new maplibregl.Map({container:"map",center:[-50.3,-14.08],zoom:7,style:{version:8,sources:{osm:{type:"raster",tiles:["https://tile.openstreetmap.org/{z}/{x}/{y}.png"],tileSize:256,attribution:"© OpenStreetMap"}},layers:[{id:"osm",type:"raster",source:"osm"}]}});map.addControl(new maplibregl.NavigationControl(),"top-right");map.on("load",()=>{map.addSource("axis",{type:"geojson",data:{type:"Feature",geometry:{type:"LineString",coordinates:axis.map(p=>p.coordinate)}}});map.addLayer({id:"axis",type:"line",source:"axis",paint:{"line-color":"#082b4c","line-width":3}});map.addSource("track",{type:"geojson",data:{type:"FeatureCollection",features:[]}});map.addLayer({id:"track",type:"line",source:"track",paint:{"line-color":"#f28b22","line-width":4,"line-opacity":.85}});renderReplay(replayCurrent)})}
function renderMap(tracks){if(!map?.getSource("track"))return;const features=tracks.filter(v=>v.length>1).map(v=>({type:"Feature",properties:{},geometry:{type:"LineString",coordinates:v.map(p=>p.projection.coordinate)}}));map.getSource("track").setData({type:"FeatureCollection",features});const all=tracks.flat();if(all.length){const b=new maplibregl.LngLatBounds();all.forEach(p=>b.extend(p.projection.coordinate));map.fitBounds(b,{padding:45,maxZoom:14})}}
function setupReplay(points){replayGroups=new Map();for(const p of points){if(!p.projection)continue;const id=p.equipment_id;if(!replayGroups.has(id))replayGroups.set(id,[]);replayGroups.get(id).push(p)}for(const a of replayGroups.values())a.sort((x,y)=>Date.parse(x.captured_at)-Date.parse(y.captured_at));replayStart=points.length?Date.parse(points[0].captured_at):0;replayEnd=points.length?Date.parse(points.at(-1).captured_at):0;replayCurrent=replayEnd;e.replayRange.value=1000;stopReplay();renderReplay(replayCurrent)}
function lastBefore(points,t){let lo=0,hi=points.length-1,best=null;while(lo<=hi){const m=(lo+hi)>>1;if(Date.parse(points[m].captured_at)<=t){best=points[m];lo=m+1}else hi=m-1}return best}
function renderReplay(t){e.replayTime.textContent=t?date(new Date(t)):"Sem sinais";for(const [id,points] of replayGroups){const p=lastBefore(points,t);if(!p||t-Date.parse(p.captured_at)>600000){replayMarkers.get(id)?.remove();replayMarkers.delete(id);continue}let marker=replayMarkers.get(id);if(!marker&&map){const el=document.createElement("div");el.className="replay-marker";el.dataset.label=id;marker=new maplibregl.Marker({element:el}).setLngLat(p.projection.coordinate).addTo(map);replayMarkers.set(id,marker)}marker?.setLngLat(p.projection.coordinate)}}
function stopReplay(){clearInterval(replayTimer);replayTimer=null;e.replayToggle.textContent="▶ REPRODUZIR"}
function toggleReplay(){if(replayTimer){stopReplay();return}if(replayCurrent>=replayEnd)replayCurrent=replayStart;e.replayToggle.textContent="Ⅱ PAUSAR";replayTimer=setInterval(()=>{replayCurrent+=Number(e.replaySpeed.value)*250;if(replayCurrent>=replayEnd){replayCurrent=replayEnd;stopReplay()}e.replayRange.value=replayEnd===replayStart?1000:(replayCurrent-replayStart)/(replayEnd-replayStart)*1000;renderReplay(replayCurrent)},250)}
function renderAlerts(latest){const now=Date.parse(latest.serverTime||new Date()),items=[],rank={high:0,medium:1,info:2};for(const x of latest.equipment||[]){const id=x.equipmentId,seconds=x.receivedAt?(now-Date.parse(x.receivedAt))/1000:Infinity;if(!x.receivedAt)items.push({level:"info",title:`${id} sem sinal`,text:"Nenhuma posição recebida no histórico disponível."});else{if(seconds>120)items.push({level:"high",title:`${id} offline`,text:`Último sinal há ${age(seconds)} · ${x.operatorName||"sem operador"}.`});else if(seconds>30)items.push({level:"medium",title:`${id} com sinal instável`,text:`Última atualização há ${age(seconds)}.`});if(Number(x.battery)<20)items.push({level:"medium",title:`Bateria baixa · ${id}`,text:`Bateria informada em ${x.battery}%.`});if(Number(x.accuracy)>GPS_MAX_PRECISION_M)items.push({level:"medium",title:`Precisão insuficiente · ${id}`,text:`Margem atual de ${Math.round(x.accuracy)} m; posição excluída dos indicadores.`});const pr=project(x);if(pr&&pr.distanceM>100)items.push({level:"high",title:`${id} fora da faixa`,text:`Sinal a ${Math.round(pr.distanceM)} m do eixo da linha tronco.`});}}items.sort((a,b)=>rank[a.level]-rank[b.level]);e.alertCount.textContent=items.filter(x=>x.level!=="info").length;e.alerts.replaceChildren();if(!items.length){e.alerts.innerHTML='<div class="empty">Nenhum alerta ativo.</div>';return}for(const x of items){const d=document.createElement("div");d.className=`alert ${x.level}`;d.innerHTML=`<strong></strong><span></span>`;d.querySelector("strong").textContent=x.title;d.querySelector("span").textContent=x.text;e.alerts.append(d)}}
function renderEvents(data,m){const items=[];for(const s of data.sessions){items.push({time:s.started_at,title:`Turno iniciado · ${s.equipment_id}`,text:`${s.operator_name} (${s.operator_registration}) assumiu o equipamento.`});if(s.ended_at)items.push({time:s.ended_at,title:`Turno encerrado · ${s.equipment_id}`,text:`Motivo: ${s.ended_reason||"encerramento registrado"}.`})}const groups=data.positions.reduce((o,p)=>((o[p.equipment_id]||=[]).push(p),o),{});for(const [id,ps] of Object.entries(groups)){ps.sort((a,b)=>Date.parse(a.captured_at)-Date.parse(b.captured_at));for(let i=1;i<ps.length;i++){const gap=(Date.parse(ps[i].captured_at)-Date.parse(ps[i-1].captured_at))/1000;if(gap>120)items.push({time:ps[i].captured_at,title:`Retorno de sinal · ${id}`,text:`Intervalo sem telemetria de ${duration(gap)}.`,warning:true})}let anchor=null,start=null,lastEvent=0;for(const p of ps){if(!p.projection)continue;if(anchor===null||Math.abs(p.projection.stationM-anchor)>GPS_DEADBAND_M){anchor=p.projection.stationM;start=Date.parse(p.captured_at)}else if(Date.parse(p.captured_at)-start>=600000&&Date.parse(p.captured_at)-lastEvent>600000){items.push({time:p.captured_at,title:`Parada prolongada · ${id}`,text:`Imobilidade confirmada por pelo menos 10 minutos no km ${(p.projection.stationM/1000).toFixed(3).replace(".","+")}.`,warning:true});lastEvent=Date.parse(p.captured_at)}}}if(m.rejected)items.push({time:data.generatedAt,title:"Qualidade do GPS",text:`${m.rejected.toLocaleString("pt-BR")} sinais excluídos por precisão ou distância do eixo.`,warning:true});items.sort((a,b)=>Date.parse(b.time)-Date.parse(a.time));e.eventCount.textContent=items.length;e.events.replaceChildren();if(!items.length){e.events.innerHTML='<div class="empty">Nenhum evento relevante no período.</div>';return}for(const x of items.slice(0,100)){const d=document.createElement("div");d.className=`event${x.warning?" warning":""}`;d.innerHTML="<strong></strong><span></span>";d.querySelector("strong").textContent=x.title;d.querySelector("span").textContent=`${date(x.time)} · ${x.text}`;e.events.append(d)}}
function populate(data){if(e.equipment.options.length===1)data.equipment.forEach(x=>e.equipment.add(new Option(`${x.id} · ${x.name}`,x.id)));if(e.operator.options.length===1)data.operators.forEach(x=>e.operator.add(new Option(`${x.name} · ${x.registration}`,x.registration)))}
async function load(){notify(e.message,"");const button=e.filters.querySelector('button:not([type="button"])');button.disabled=true;try{const body={adminPassword:password,equipmentId:e.equipment.value||null,registration:e.operator.value||null,from:new Date(e.from.value).toISOString(),to:new Date(e.to.value).toISOString()};const [rr,lr]=await Promise.all([fetch(`${API}/api/v2/admin/operations/report`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),fetch(`${API}/api/v1/equipment/latest`)]);const data=await rr.json(),latest=await lr.json();if(!rr.ok)throw new Error(data.error||"Falha na consulta.");if(!lr.ok)throw new Error(latest.error||"Falha ao consultar a frota.");populate(data);const m=calculate(data.positions,data.sessions);renderKpis(m);renderSessions(data.sessions);renderChart(m.timeline);renderMap(m.tracks);setupReplay(m.timeline);renderAlerts(latest);renderEvents(data,m);const sampled=data.positions.some(p=>Date.parse(p.captured_at)<Date.now()-7*86400000);e.source.textContent=`${sampled?"Sinais originais + amostra de 1 min":"Sinais originais"} · filtro ${GPS_DEADBAND_M} m · precisão ≤ ${GPS_MAX_PRECISION_M} m`;e.freshness.textContent=`Relatório gerado em ${date(data.generatedAt)} · ${data.positions.length.toLocaleString("pt-BR")} sinais · ${m.suppressed.toLocaleString("pt-BR")} oscilações suprimidas`}catch(err){notify(e.message,err.message);throw err}finally{button.disabled=false}}
e.accessForm.addEventListener("submit",async ev=>{ev.preventDefault();password=e.password.value;notify(e.accessMessage,"");try{if(!axis.length){const data=await fetch(AXIS).then(r=>r.json());prepareAxis(data.points);initMap()}await load();e.access.hidden=true;e.dashboard.hidden=false;setTimeout(()=>map.resize(),0)}catch(err){password="";notify(e.accessMessage,err.message)}});e.filters.addEventListener("submit",ev=>{ev.preventDefault();load().catch(()=>{})});e.replayToggle.addEventListener("click",toggleReplay);e.replayRange.addEventListener("input",()=>{stopReplay();replayCurrent=replayStart+(replayEnd-replayStart)*Number(e.replayRange.value)/1000;renderReplay(replayCurrent)});e.print.addEventListener("click",()=>window.print());
