const API = /^(?:localhost|127\.0\.0\.1)$/.test(location.hostname) ? 'http://127.0.0.1:8791' : 'https://fico-tracking-api.automacaofico.workers.dev';
const $ = (id) => document.getElementById(id);
let password = '';
const notify = (element, text, success = false) => { element.textContent = text; element.hidden = !text; element.classList.toggle('success', success); };
async function api(path, body = {}) { const response = await fetch(`${API}${path}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ adminPassword: password, ...body }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || `HTTP ${response.status}`); return data; }
function edit(item, type) { if (type === 'requester') { $('requester-code').value = item.code; $('requester-name').value = item.name; $('requester-role').value = item.role || ''; $('requester-company').value = item.company || ''; $('requester-supervisor').value = item.supervisor || ''; $('requester-name').focus(); } else { $('cco-code').value = item.code; $('cco-name').value = item.name; $('cco-pin').value = ''; $('cco-name').focus(); } scrollTo({ top: 0, behavior: 'smooth' }); }
function row(item, type) { const element = document.createElement('div'); element.className = `admin-row ${item.active ? '' : 'inactive'}`; element.innerHTML = '<div><strong></strong><span></span></div><div class="admin-actions"><button data-edit>EDITAR</button><button data-status></button></div>'; element.querySelector('strong').textContent = `${item.code} · ${item.name}`; element.querySelector('span').textContent = type === 'requester' ? `${item.role || 'Função não informada'} · ${item.company || 'Empresa não informada'}` : 'Acesso individual do CCO'; element.querySelector('[data-edit]').onclick = () => edit(item, type); const button = element.querySelector('[data-status]'); button.textContent = item.active ? 'DESATIVAR' : 'ATIVAR'; button.onclick = async () => { if (!confirm(`${button.textContent} ${item.code}?`)) return; try { await api(`/api/v2/admin/cco/${type === 'requester' ? 'requesters' : 'controllers'}/status`, { code: item.code, name: item.name, active: !item.active }); await load(); } catch (error) { notify($('message'), error.message); } }; return element; }
async function load() { const [requesters, controllers] = await Promise.all([api('/api/v2/admin/cco/requesters/list'), api('/api/v2/admin/cco/controllers/list')]); $('requester-count').textContent = requesters.requesters.length; $('controller-count').textContent = controllers.controllers.length; $('requesters').replaceChildren(...requesters.requesters.map((item) => row(item, 'requester'))); $('controllers').replaceChildren(...controllers.controllers.map((item) => row(item, 'controller'))); }
$('access-form').onsubmit = async (event) => { event.preventDefault(); password = $('admin-password').value; try { await load(); $('access').hidden = true; $('content').hidden = false; } catch (error) { password = ''; notify($('access-message'), error.message); } };
$('requester-form').onsubmit = async (event) => { event.preventDefault(); try { await api('/api/v2/admin/cco/requesters/save', { code: $('requester-code').value, name: $('requester-name').value, role: $('requester-role').value, company: $('requester-company').value, supervisor: $('requester-supervisor').value }); event.target.reset(); notify($('message'), 'Solicitante salvo.', true); await load(); } catch (error) { notify($('message'), error.message); } };
$('controller-form').onsubmit = async (event) => { event.preventDefault(); try { await api('/api/v2/admin/cco/controllers/save', { code: $('cco-code').value, name: $('cco-name').value, pin: $('cco-pin').value }); event.target.reset(); notify($('message'), 'Controlador salvo.', true); await load(); } catch (error) { notify($('message'), error.message); } };
